#!/bin/sh

# Core
alias v='nvim'
alias c='clear'
alias ls='ls --color'

# Utils
alias ff="fd --type f | fzf | sed 's/\ /\\\ /g' | xargs nvim"
alias mail="neomutt"
alias rss='newsboat'

# CD
alias dev='cd ~/Developer'
alias vault='cd ~/Notes/obsidian-vault'
alias til='cd ~/Notes/today_i_learned'

# Fun
alias info='fastfetch'
alias weather="curl wttr.in"
alias astroterm='astroterm --color --constellations --speed 1000 --fps 120 --city Dallas'

# linear-cli
alias lc='linear-cli issues create'
alias lls='linear-cli issues list'
