# Reference: https://github.com/i3/i3/blob/next/etc/config

# Start AeroSpace at login
start-at-login = true

# Notify sketchybar on workspace change
exec-on-workspace-change = [
    '/bin/bash',
    '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 20

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

automatically-unhide-macos-hidden-apps = true


[key-mapping]
preset = 'qwerty'


[gaps]
outer.top = 32
outer.bottom = 10
outer.left = 30
outer.right = 30
inner.horizontal = 10
inner.vertical = 10

[mode.main.binding]

    # i3 wraps focus by default
    alt-h =         'focus --boundaries-action wrap-around-the-workspace left'
    alt-j =         'focus --boundaries-action wrap-around-the-workspace down'
    alt-k =         'focus --boundaries-action wrap-around-the-workspace up'
    alt-l =         'focus --boundaries-action wrap-around-the-workspace right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # Consider using 'join-with' command as a 'split' replacement if you want to enable
    # normalizations
    alt-v = 'join-with right'

    alt-f = 'fullscreen'

    alt-slash = 'layout tiles horizontal vertical'
    alt-semicolon = 'layout accordion horizontal vertical'

    alt-t = 'layout tiling'
    alt-shift-f = 'layout floating'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    alt-0 = 'workspace 10'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
    alt-shift-0 = 'move-node-to-workspace 10'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
    alt-tab = 'workspace-back-and-forth'
    # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    alt-shift-c = 'reload-config'

    alt-shift-r = 'mode resize'

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'

# Floating window assignments
[[on-window-detected]]
if.app-id = 'com.apple.DiskUtility'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.ScreenContinuity'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.daisydiskapp.DaisyDiskStandAlone'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.Arturia.ArturiaSoftwareCenter'
run = 'layout floating'

# [[on-window-detected]]
# if.app-id = 'com.josephlyncheski.minimeters'
# run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.AppStore'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.backup.launcher'
run = 'layout floating'

# [[on-window-detected]]
# if.app-id = 'com.bitwarden.desktop'
# run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.raycast.app'
run = 'layout floating'
