# preload = ~/Pictures/Small Boat and Lake.jpg
# wallpaper = monitor, ~/Pictures/Small Boat and Lake.jpg

# You can find more wallpapers in ~/.config/ml4w/wallpapers/
# Run ~/.config/hypr/reload-hyprpaper.sh after changing your wallpaper
preload = ~/Pictures/Evangelion.png
wallpaper = ~/Pictures/Evangelion.png
splash = false
