[general]
import = [ "~/.config/alacritty/themes/nord.toml"]

[window]
padding = { x = 5, y = 5}
decorations = "None"
opacity = 0.8
blur = true
dynamic_title = true

[font]
# normal = { family = "Iosevka Nerd Font Mono", style = "Regular" }
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 14.00

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

